# Лабораторная работа на тему "Прямые методы решения слау"

### Вариант 10
Эскалаторный метод решения слау

##### описание метода


In [307]:
import numpy as np

In [ ]:
def solve(A: np.ndarray, b: np.ndarray):
    n = A.shape[0]
    Ab = np.concatenate((A, np.expand_dims(-b, axis=1)), axis=1)
    Ab = np.concatenate((Ab, np.array([np.append(-b, 0)])), axis=0)
    
    Z = np.eye(n + 1)
    C = np.zeros((n, n))
    G = np.zeros((n, n))
    
    for k in range(n):
        for j in range(k + 1):
            for i in range(j, n):
                C[i, j] = sum(Ab[i,s] * Z[s, j] for s in range(j + 1))
            
            for i in range(j, n):
                G[i, j] = C[i, j] / C[j, j]
        
        g = np.zeros(k + 1)
        for j in range(k + 1):
            c_kj = sum(Ab[k+1,s] * Z[s, j] for s in range(j + 1))
            g[j] = c_kj / C[j, j]
        
        for i in range(k, -1, -1):
            Z[i, k+1] = -g[i] - sum(Z[i, s] * g[s] for s in range(i + 1, k + 1))

    x = Z[:n, n]
    return x, Z, C, G



In [309]:
A = np.array([
    [12, 1.5, 2, 2.5, 1],
    [1.5, 10, 1.2, 1.8, 0.9],
    [2, 1.2, 14, 3, 1.5],
    [2.5, 1.8, 3, 16, 1.8],
    [1, 0.9, 1.5, 1.8, 15]
])

b = np.array([8.5, 6.3, 10.2, 12.8, 7.1])

In [310]:
x, Z, C, G = solve(A, b)

print('Z', np.array(Z))
print('C', np.array(C))
print('Г', np.array(G))

xn = np.linalg.solve(A, b)
# xn = np.linalg.solve(A, b)
print('эскалаторный метод, x:', x)
print('numpy, x:', xn)
print('разница:', x - xn)

Z [[ 1.         -0.125      -0.15456476 -0.16160959 -0.04551911  0.43803631]
 [ 0.          1.         -0.09681529 -0.13419502 -0.0587018   0.37754672]
 [ 0.          0.          1.         -0.1796962  -0.07755673  0.47986729]
 [ 0.          0.          0.          1.         -0.0842418   0.56471356]
 [ 0.          0.          0.          0.          1.          0.30572575]
 [ 0.          0.          0.          0.          0.          1.        ]]
C [[12.          0.          0.          0.          0.        ]
 [ 1.5         9.8125      0.          0.          0.        ]
 [ 2.          0.95       13.57469214  0.          0.        ]
 [ 2.5         1.4875      2.43932059 14.81533639  0.        ]
 [ 1.          0.775       1.25830149  1.24807059 14.63367893]]
Г [[1.         0.         0.         0.         0.        ]
 [0.125      1.         0.         0.         0.        ]
 [0.16666667 0.09681529 1.         0.         0.        ]
 [0.20833333 0.15159236 0.1796962  1.         0.     

In [311]:
my_solving = solve(A, b)
my_solving

(array([0.43803631, 0.37754672, 0.47986729, 0.56471356, 0.30572575]),
 array([[ 1.        , -0.125     , -0.15456476, -0.16160959, -0.04551911,
          0.43803631],
        [ 0.        ,  1.        , -0.09681529, -0.13419502, -0.0587018 ,
          0.37754672],
        [ 0.        ,  0.        ,  1.        , -0.1796962 , -0.07755673,
          0.47986729],
        [ 0.        ,  0.        ,  0.        ,  1.        , -0.0842418 ,
          0.56471356],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
          0.30572575],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          1.        ]]),
 array([[12.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 1.5       ,  9.8125    ,  0.        ,  0.        ,  0.        ],
        [ 2.        ,  0.95      , 13.57469214,  0.        ,  0.        ],
        [ 2.5       ,  1.4875    ,  2.43932059, 14.81533639,  0.        ],
        [ 1.        ,  0.775     ,  1.25830149

In [312]:
np_solving = np.linalg.solve(A, b)
np_solving

array([0.43803631, 0.37754672, 0.47986729, 0.56471356, 0.30572575])

In [313]:
max_error = 0
for np_x, my_x in zip(np_solving, my_solving):
    max_error = max(max_error, np.max(np.abs(np_x - my_x)))
max_error

np.float64(14.335469107835465)