# Лабораторная работа по теме Итерационные методы решения слау

### Вариант 4
Метод наискорейшего градиентного спуска
(с 455)

##### описание метода
Метод наискорейшего градиентного спуска применяется для решения системы линейных алгебраических уравнений (СЛАУ) вида: $Ax=b$ \
где \
A - симметричная положительно определенная матрица n×n \
x - вектор неизвестных \
b - вектор правых частей

In [75]:
import numpy as np

In [76]:
def solve(
    A: np.ndarray,
    b: np.ndarray,
    eps: float = 1e-15,
) -> tuple[np.ndarray]:
    """
    Решение системы методом наискорейшего градиентного спуска
    residual - невязка
    """
    
    """
    этап 1:
    готовим начальные x и невязку
    которая будет выполнять роль отслеживания насколько близко мы находимся к решению
    """
    n = A.shape[0]
    x = np.zeros(n)
    x_new = np.ones(n)
    residual = A @ x - b
    residual_new = residual

    it_counter = 0

    while np.all(abs(x - x_new) > eps):
        it_counter += 1
        x = x_new
        residual = residual_new
        """
        этап 2:
        на основе вектора невязки вычисляем оптимальный шаг alpha
        alpha_k = (r_k, r_k) / (Ar_k, r_k)
        и обновляем решение
        """
        alpha = np.dot(residual, residual) / np.dot(A @ residual, residual)
        x_new = x - alpha * residual
        
        """
        этап 3:
        вычисляем новую невязку по новому решению
        r_k = F - AX_k
        """
        residual_new = A @ x_new - b

        if it_counter % 100 == 0:
            print(f"{it_counter=}: невязка={np.linalg.norm(residual_new):.6e}")

    print(f"Итоги: {it_counter=}, невязка={np.linalg.norm(residual_new):.6e}")
    
    return x
    

In [77]:
def check_input_matrix(A: np.ndarray, b: np.ndarray) -> bool:
    eigvals = np.linalg.eigvals(A)
    if np.any(eigvals <= 0):
        return False
    
    return np.all(np.linalg.solve(A, b))

In [78]:
def generate(size: int = 4, tryings: int = 10**7) -> tuple[np.ndarray, np.ndarray]:
    for _ in range(tryings):
        # A_random = np.random.randn(size, size)
        A_random = np.random.randint(-100, 100, size=(size, size))
        A = (A_random + A_random.T)

        b = np.random.randint(-100, 100, size=(size))
        if check_input_matrix(A, b):
            return A, b

In [79]:
def test(A: np.ndarray, b: np.ndarray) -> None:
    print(f"исходная матрица A {A}")
    print(f"исходный вектор b {b}")
    print(f"проверка на валидность входных данных {check_input_matrix(A, b)}")

    my_x = solve(A, b)
    np_x = np.linalg.solve(A, b)
    error = abs(my_x - np_x)

    print(
        f"мой x: {my_x}",
        f"точный x: {np_x}",
        f"Ошибка: {error}",
        f"Максимальная ошибка: {np.max(error):.6e}",
        sep="\n"
    )

In [80]:
# Тест: Простая симметричная матрица
A = np.array([
    [2, 1],
    [1, 2],
], dtype=float)
b = np.array([1,1])
test(A, b)

исходная матрица A [[2. 1.]
 [1. 2.]]
исходный вектор b [1 1]
проверка на валидность входных данных True
Итоги: it_counter=3, невязка=0.000000e+00
мой x: [0.33333333 0.33333333]
точный x: [0.33333333 0.33333333]
Ошибка: [1.11022302e-16 5.55111512e-17]
Максимальная ошибка: 1.110223e-16


In [81]:
A, b = generate(size=6)

In [82]:
test(A, b)

исходная матрица A [[ 110  -37   35    9 -108  -27]
 [ -37  198 -111  -13    1  -29]
 [  35 -111  196  -76  -22   51]
 [   9  -13  -76  178    5   25]
 [-108    1  -22    5  148    4]
 [ -27  -29   51   25    4  132]]
исходный вектор b [ 82  26 -13 -73 -93 -61]
проверка на валидность входных данных True
it_counter=100: невязка=4.496483e-04
it_counter=200: невязка=4.941934e-06
it_counter=300: невязка=5.431520e-08
it_counter=400: невязка=5.969658e-10
Итоги: it_counter=499, невязка=7.521185e-12
мой x: [ 1.25858959e+00  1.20402567e-03 -6.03945984e-01 -7.61112677e-01
  2.21484934e-01  1.66363319e-01]
точный x: [ 1.25858959e+00  1.20402567e-03 -6.03945984e-01 -7.61112677e-01
  2.21484934e-01  1.66363319e-01]
Ошибка: [5.02931030e-13 5.58695885e-14 1.26454403e-13 1.09912079e-13
 3.73173714e-13 1.77857729e-13]
Максимальная ошибка: 5.029310e-13
